# Site settings
title: "Zahra Shahin"
description: "A resume for Zahra Shahin"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Zahra Shahin"
resume_title:                   "Mobile Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "zshahin.61@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "416-625612"
resume_contact_address:         "Newmarket, Ontario"

resume_header_contact_info:     "Newmarket,Ontario • 416-625612 • zshahin.61@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Software developer experienced in object-oriented analysis and design, implementation of databases, and development of dynamic web applications.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     false
# resume_section_links:           false
# resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://zshahin-61.github.io"
 # resume_twitter_url:           "http://twitter.com/jglovier"
  #  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "www.linkedin.com/in/zahra-shahin"
  # resume_instagram_url:         "insert your Instagram URL here"
 # resume_website_url:           "http://joelglovier.com"
 # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
